language: node_js

os: linux

dist: xenial

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      script:
        - npm run validate
        - npm run build
      after_success:
        - npx codecov
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
