language: node_js

os: linux

dist: xenial

node_js: lts/*

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run coverage:test
        - npm run coverage:check
        - npm run build
      after_success:
        - npx codecov
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
