language: node_js

os: linux

dist: xenial

node_js: lts/*

script:
  - npm run coverage:test
  - npm run coverage:check
  - npm run build

after_success:
  - npx codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        cleanup: false
        script: npx semantic-release
