language: node_js

os: linux

dist: xenial

node_js: lts/*

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run coverage:test
        - npm run coverage:check
        - npm run build
      deploy:
        provider: script
        cleanup: false
        script: npx semantic-release
        after_success:
          - npx codecov
